/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'
import { Route as SellerVerificationRouteImport } from './routes/seller.verification'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerOnboardingRouteImport } from './routes/seller.onboarding'
import { Route as PartnerProfileRouteImport } from './routes/partner.profile'
import { Route as PartnerEarningsRouteImport } from './routes/partner.earnings'
import { Route as PartnerDeliveriesRouteImport } from './routes/partner.deliveries'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ApiDocsOpenapiDotjsonRouteImport } from './routes/api-docs.openapi[.]json'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as SellerTrackOrderIdRouteImport } from './routes/seller.track.$orderId'
import { Route as PartnerTrackOrderIdRouteImport } from './routes/partner.track.$orderId'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api.webhooks.razorpay'
import { Route as ApiLiveOrderOrderIdRouteImport } from './routes/api.live.order.$orderId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerVerificationRoute = SellerVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SellerRoute,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerEarningsRoute = PartnerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDeliveriesRoute = PartnerDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => PartnerRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsOpenapiDotjsonRoute = ApiDocsOpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => ApiDocsRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const SellerTrackOrderIdRoute = SellerTrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => SellerRoute,
} as any)
const PartnerTrackOrderIdRoute = PartnerTrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => PartnerRoute,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveOrderOrderIdRoute = ApiLiveOrderOrderIdRouteImport.update({
  id: '/api/live/order/$orderId',
  path: '/api/live/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/api-docs/openapi.json': typeof ApiDocsOpenapiDotjsonRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/partner/deliveries': typeof PartnerDeliveriesRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/partner/track/$orderId': typeof PartnerTrackOrderIdRoute
  '/seller/track/$orderId': typeof SellerTrackOrderIdRoute
  '/api/live/order/$orderId': typeof ApiLiveOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/api-docs': typeof ApiDocsRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/api-docs/openapi.json': typeof ApiDocsOpenapiDotjsonRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/partner/deliveries': typeof PartnerDeliveriesRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/admin': typeof AdminIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/partner/track/$orderId': typeof PartnerTrackOrderIdRoute
  '/seller/track/$orderId': typeof SellerTrackOrderIdRoute
  '/api/live/order/$orderId': typeof ApiLiveOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/api-docs/openapi.json': typeof ApiDocsOpenapiDotjsonRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/partner/deliveries': typeof PartnerDeliveriesRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/verification': typeof SellerVerificationRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/partner/track/$orderId': typeof PartnerTrackOrderIdRoute
  '/seller/track/$orderId': typeof SellerTrackOrderIdRoute
  '/api/live/order/$orderId': typeof ApiLiveOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addresses'
    | '/admin'
    | '/api-docs'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/partner'
    | '/payments'
    | '/search'
    | '/sell'
    | '/seller'
    | '/settings'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/shops'
    | '/admin/verification'
    | '/api-docs/openapi.json'
    | '/order/$orderId'
    | '/partner/deliveries'
    | '/partner/earnings'
    | '/partner/profile'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/settings'
    | '/seller/verification'
    | '/shop/$shopId'
    | '/admin/'
    | '/partner/'
    | '/seller/'
    | '/api/webhooks/razorpay'
    | '/partner/track/$orderId'
    | '/seller/track/$orderId'
    | '/api/live/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addresses'
    | '/api-docs'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/payments'
    | '/search'
    | '/sell'
    | '/settings'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/shops'
    | '/admin/verification'
    | '/api-docs/openapi.json'
    | '/order/$orderId'
    | '/partner/deliveries'
    | '/partner/earnings'
    | '/partner/profile'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/settings'
    | '/seller/verification'
    | '/shop/$shopId'
    | '/admin'
    | '/partner'
    | '/seller'
    | '/api/webhooks/razorpay'
    | '/partner/track/$orderId'
    | '/seller/track/$orderId'
    | '/api/live/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/addresses'
    | '/admin'
    | '/api-docs'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/partner'
    | '/payments'
    | '/search'
    | '/sell'
    | '/seller'
    | '/settings'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/shops'
    | '/admin/verification'
    | '/api-docs/openapi.json'
    | '/order/$orderId'
    | '/partner/deliveries'
    | '/partner/earnings'
    | '/partner/profile'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/settings'
    | '/seller/verification'
    | '/shop/$shopId'
    | '/admin/'
    | '/partner/'
    | '/seller/'
    | '/api/webhooks/razorpay'
    | '/partner/track/$orderId'
    | '/seller/track/$orderId'
    | '/api/live/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  ApiLiveOrderOrderIdRoute: typeof ApiLiveOrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/verification': {
      id: '/seller/verification'
      path: '/verification'
      fullPath: '/seller/verification'
      preLoaderRoute: typeof SellerVerificationRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/partner/profile': {
      id: '/partner/profile'
      path: '/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/earnings': {
      id: '/partner/earnings'
      path: '/earnings'
      fullPath: '/partner/earnings'
      preLoaderRoute: typeof PartnerEarningsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/deliveries': {
      id: '/partner/deliveries'
      path: '/deliveries'
      fullPath: '/partner/deliveries'
      preLoaderRoute: typeof PartnerDeliveriesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/openapi.json': {
      id: '/api-docs/openapi.json'
      path: '/openapi.json'
      fullPath: '/api-docs/openapi.json'
      preLoaderRoute: typeof ApiDocsOpenapiDotjsonRouteImport
      parentRoute: typeof ApiDocsRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/track/$orderId': {
      id: '/seller/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/seller/track/$orderId'
      preLoaderRoute: typeof SellerTrackOrderIdRouteImport
      parentRoute: typeof SellerRoute
    }
    '/partner/track/$orderId': {
      id: '/partner/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/partner/track/$orderId'
      preLoaderRoute: typeof PartnerTrackOrderIdRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/order/$orderId': {
      id: '/api/live/order/$orderId'
      path: '/api/live/order/$orderId'
      fullPath: '/api/live/order/$orderId'
      preLoaderRoute: typeof ApiLiveOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiDocsRouteChildren {
  ApiDocsOpenapiDotjsonRoute: typeof ApiDocsOpenapiDotjsonRoute
}

const ApiDocsRouteChildren: ApiDocsRouteChildren = {
  ApiDocsOpenapiDotjsonRoute: ApiDocsOpenapiDotjsonRoute,
}

const ApiDocsRouteWithChildren =
  ApiDocsRoute._addFileChildren(ApiDocsRouteChildren)

interface PartnerRouteChildren {
  PartnerDeliveriesRoute: typeof PartnerDeliveriesRoute
  PartnerEarningsRoute: typeof PartnerEarningsRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  PartnerTrackOrderIdRoute: typeof PartnerTrackOrderIdRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerDeliveriesRoute: PartnerDeliveriesRoute,
  PartnerEarningsRoute: PartnerEarningsRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  PartnerTrackOrderIdRoute: PartnerTrackOrderIdRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface SellerRouteChildren {
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerVerificationRoute: typeof SellerVerificationRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerTrackOrderIdRoute: typeof SellerTrackOrderIdRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerVerificationRoute: SellerVerificationRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerTrackOrderIdRoute: SellerTrackOrderIdRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiDocsRoute: ApiDocsRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ShopShopIdRoute: ShopShopIdRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  ApiLiveOrderOrderIdRoute: ApiLiveOrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
